name: deploy

on:
  workflow_dispatch:

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: npm
      - run: npm install --immutable
      - run: npm vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
      - run: npm vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}
      - run: npm vercel deploy --prod --prebuilt --token=${{ secrets.VERCEL_TOKEN }}